name: "BunnyCDN storage deployer"
description: "BunnyCDN storage deployer"
inputs:
  source:
    description: "The source directory folder."
    required: true
  storageZoneName:
    description: "The name of your storage zone where you are connecting to."
    required: true
  storagePassword:
    description: "The storage password. It should be read and write capable."
  storageEndpoint:
    description: "The storage endpoint"
    default: "storage.bunnycdn.com"
  accessKey:
    description: "The API key."
  pullZoneId:
    description: "Is required for purging."
  purgePullZone:
    description: "It will purge the pull zone if true. pullZoneId and accessKey should be provided."
    default: "false"
  remove:
    description: "It will remove the files from storage before uploading if 'true' provided."
    default: "false"

runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "orange"
